language:
  - cpp
  - python
python:
  - "2.7"
  - "3.3"
compiler:
  - gcc
  - clang
# command to install dependencies
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-rosdep python-catkin-pkg python-nose python-coverage python-wstool pep8 -qq
  - sudo apt-get install ros-hydro-catkin -qq
  - sudo rosdep init
  - rosdep update
  # Make a workspace
  - mkdir -p /tmp/ros_dynamic_reconfigure_ws/src
  # Add this folder to the workspace
  - ln -s `pwd` /tmp/dynamic_reconfigure_ws/src/dynamic_reconfigure
  # Install dependencies
  - cd /tmp/dynamic_reconfigure_ws
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y > /dev/null
# command to run tests
script:
  - source /opt/ros/hydro/setup.bash
  - cd /tmp/dynamic_reconfigure_ws
  - catkin_make tests > log.make_tests
  - cd build
  # Manually invoke make, catkin_make
  - make run_tests > log.run_tests || cat log.*
  # Check test results
  - 'python -c "from catkin.test_results import test_results;import sys;sys.exit(sum([v[1] + v[2] for k, v in test_results(\"test_results\").items()]))" || cat log*'
  - 'python -c "from catkin.test_results import test_results;import sys;sys.exit(sum([v[1] + v[2] for k, v in test_results(\"test_results\").items()]))"'
notifications:
  email: false
